// Ball.js — the match ball.
//
// It used to be `add.circle(x, y, 6, 0xffffff)`: a white dot with a dark stroke.
// At a glance that reads as a bug rather than a football, and because a circle has
// no features it cannot show rotation, so a 30-yard pass looked like a dot
// sliding across the grass.
//
// This module fixes both. The ball is a real panelled football, and the panels
// are generated by sampling a sphere, so rotating that sphere produces a frame
// strip the ball can be cycled through as it travels. Spin comes out of the
// distance covered rather than a timer, which means it accelerates off a shot and
// dies away as the ball settles, for free.
//
// Style rules it has to obey (see AGENTS.md → Art API contract):
//   * chunky pixels at the same scale as the chibi (px = 2), never smooth vectors
//   * a dark outline all the way round, same treatment as the characters
//   * baked into a texture once, not redrawn per frame

import { C } from './Palette.js';

const KEY = 'matchball';

const FRAMES = 12;   // rotation phases; 12 is smooth enough at this size
export const BALL_FRAMES = FRAMES;
const GRID = 8;      // ball is GRID x GRID chunky pixels
const PX = 2;        // screen pixels per chunky pixel  ->  16px ball
// PAD 1 would be enough for the outline, but the frames are packed edge to edge
// in one strip. Without a transparent gutter the renderer samples the
// neighbouring frame along each border and the ball picks up a ghost rim.
const PAD = 2;
const CELL = (GRID + PAD * 2) * PX;

// Leather and panels, lit tone first. Only two steps each: at 16px across, a
// three-tone ramp plus a 2px outline leaves so few pure-white cells that the
// ball turns grey and stops reading as a football at all.
const LIGHT = [0xffffff, 0xdfe6f2];
const PANEL = [0x333a4f, 0x232838];
const OUTLINE = 0x14171f;

// Light comes from the upper left, matching the chibi shading and the stand
// shadows in IsoWorld.
const LX = -0.46, LY = -0.60, LZ = 0.66;

// The 12 pentagon centres of a truncated icosahedron are the vertices of an
// icosahedron. A surface point close to one of them is on a dark panel.
const PANEL_CENTRES = (() => {
    const phi = (1 + Math.sqrt(5)) / 2;
    const raw = [];
    for (const s1 of [1, -1]) {
        for (const s2 of [1, -1]) {
            raw.push([0, s1, s2 * phi]);
            raw.push([s1, s2 * phi, 0]);
            raw.push([s2 * phi, 0, s1]);
        }
    }
    const n = Math.hypot(1, phi);
    return raw.map(([x, y, z]) => [x / n, y / n, z / n]);
})();

// How wide a panel is, as the cosine of its angular radius. Tuned by eye at
// 8x8, where a cell near the rim spans a big slice of the sphere and so
// over-claims: the geometrically correct ~25° produced a dark ball with white
// speckles, the exact inverse of a football. Lower and it muddies, higher and
// the panels break into single pixels that flicker as the ball spins.
const PANEL_COS = 0.952;

// Tumble axis. A ball rolling across the screen rotates in the image plane, but
// a pass also carries side and back spin, and a purely in-plane spin on a
// symmetrical pattern reads as a spinning coin. Tilting the axis gives panels
// that travel across the face, which is what sells it as a sphere.
const AXIS = (() => {
    const v = [0.34, 0.52, 0.78];
    const n = Math.hypot(...v);
    return v.map(c => c / n);
})();

/** Rotate a vector about a unit axis (Rodrigues). */
function spinVec([x, y, z], [ax, ay, az], ang) {
    const c = Math.cos(ang), s = Math.sin(ang);
    const dot = x * ax + y * ay + z * az;
    return [
        x * c + (ay * z - az * y) * s + ax * dot * (1 - c),
        y * c + (az * x - ax * z) * s + ay * dot * (1 - c),
        z * c + (ax * y - ay * x) * s + az * dot * (1 - c),
    ];
}

/**
 * Bake the rotation strip and register one frame per phase.
 * Cached on the texture key, so repeat scene starts reuse it.
 */
export function ensureBallTexture(scene) {
    if (scene.textures.exists(KEY)) return KEY;

    const g = scene.make.graphics({ x: 0, y: 0, add: false });

    for (let f = 0; f < FRAMES; f++) {
        const ang = (f / FRAMES) * Math.PI * 2;
        const ox = f * CELL;

        // Colour every cell of this frame first, then outline the silhouette,
        // exactly as Chibi.buildTexture does.
        const grid = [];
        for (let y = 0; y < GRID; y++) grid.push(new Array(GRID).fill(null));

        for (let y = 0; y < GRID; y++) {
            for (let x = 0; x < GRID; x++) {
                const nx = ((x + 0.5) / GRID) * 2 - 1;
                const ny = ((y + 0.5) / GRID) * 2 - 1;
                const r2 = nx * nx + ny * ny;
                if (r2 > 1) continue;                  // outside the ball

                const nz = Math.sqrt(1 - r2);
                // Surface normal in screen space. Un-rotating it by the current
                // phase gives the point's fixed home on the ball, so the pattern
                // travels while the lighting stays put.
                const home = spinVec([nx, ny, nz], AXIS, -ang);

                let near = -1;
                for (const c of PANEL_CENTRES) {
                    const d = home[0] * c[0] + home[1] * c[1] + home[2] * c[2];
                    if (d > near) near = d;
                }
                const onPanel = near > PANEL_COS;

                // Shade the side turning away from the light, and the very rim,
                // so the sphere is round rather than a flat disc. Kept to a
                // single step: the outline already darkens the whole edge.
                const lam = nx * LX + ny * LY + nz * LZ;
                const shaded = lam < 0.30 || r2 > 0.84;
                grid[y][x] = (onPanel ? PANEL : LIGHT)[shaded ? 1 : 0];
            }
        }

        // 8-neighbour outline on empty cells that touch the ball
        g.fillStyle(OUTLINE, 1);
        for (let y = -1; y <= GRID; y++) {
            for (let x = -1; x <= GRID; x++) {
                if (y >= 0 && y < GRID && x >= 0 && x < GRID && grid[y][x] !== null) continue;
                let touches = false;
                for (let dy = -1; dy <= 1 && !touches; dy++) {
                    for (let dx = -1; dx <= 1; dx++) {
                        const ny = y + dy, nx = x + dx;
                        if (ny < 0 || ny >= GRID || nx < 0 || nx >= GRID) continue;
                        if (grid[ny][nx] !== null) { touches = true; break; }
                    }
                }
                if (touches) {
                    g.fillRect(ox + (x + PAD) * PX, (y + PAD) * PX, PX, PX);
                }
            }
        }

        for (let y = 0; y < GRID; y++) {
            for (let x = 0; x < GRID; x++) {
                const col = grid[y][x];
                if (col === null) continue;
                g.fillStyle(col, 1);
                g.fillRect(ox + (x + PAD) * PX, (y + PAD) * PX, PX, PX);
            }
        }
    }

    g.generateTexture(KEY, CELL * FRAMES, CELL);
    g.destroy();

    // Slice the strip into addressable frames
    const tex = scene.textures.get(KEY);
    // Point sampling, so the chunky pixels stay chunky and the gutter stays a
    // gutter. The game does not set pixelArt globally.
    tex.setFilter(Phaser.Textures.FilterMode.NEAREST);
    for (let f = 0; f < FRAMES; f++) tex.add(f, 0, f * CELL, 0, CELL, CELL);

    return KEY;
}

/**
 * Short white impact burst — five spokes and a ring, gone in a fifth of a
 * second. Standalone so the menu kickabout can use it without a MatchBall.
 */
export function kickBurst(scene, x, y, depth, power = 1) {
    const g = scene.add.graphics().setDepth(depth);
    g.setPosition(x, y);
    const len = 8 + 6 * power;
    g.lineStyle(2, 0xffffff, 0.95);
    for (let i = 0; i < 5; i++) {
        const a = (i / 5) * Math.PI * 2 + 0.4;
        g.lineBetween(Math.cos(a) * 3, Math.sin(a) * 3,
            Math.cos(a) * len, Math.sin(a) * len);
    }
    g.lineStyle(2, C.numGold, 0.9);
    g.strokeCircle(0, 0, 4);

    scene.tweens.add({
        targets: g,
        scale: 1.9,
        alpha: 0,
        duration: 190,
        ease: 'Quad.easeOut',
        onComplete: () => g.destroy(),
    });
}

/** Grass and dust scuffed up off the turf. */
export function turfDust(scene, x, y, depth, n = 4) {
    for (let i = 0; i < n; i++) {
        const col = i % 2 ? C.grassLight : C.grassDark;
        const p = scene.add.rectangle(x, y, 3, 3, col, 0.9).setDepth(depth);
        const a = Math.random() * Math.PI * 2;
        const r = 7 + Math.random() * 11;
        scene.tweens.add({
            targets: p,
            x: x + Math.cos(a) * r,
            y: y + Math.sin(a) * r * 0.45 - 4,
            alpha: 0,
            scale: 0.4,
            duration: 260 + Math.random() * 140,
            ease: 'Quad.easeOut',
            onComplete: () => p.destroy(),
        });
    }
}

/**
 * The ball plus everything that reacts to it: ground shadow, a pulsing ground
 * marker so it stays findable among 22 sprites, an airborne trail, and the
 * impact effects for a strike.
 *
 * The scene owns field-space position; this class only ever gets screen
 * coordinates, so it does not need to know about the iso projection.
 */
export class MatchBall {
    constructor(scene, opts = {}) {
        this.scene = scene;
        const d = opts.depth ?? 8000;

        ensureBallTexture(scene);

        // Ground marker. This used to be a gold halo drawn around the ball
        // itself, which fought with the panels for the same 16px and vanished
        // the moment the ball left the floor. As a ring on the turf it reads as
        // "the ball is here" and still works with the ball in the air above it.
        //
        // White, not gold: MatchDayScene's focus marker is already a filled gold
        // ellipse under the highlighted player, and two gold ground rings a few
        // pixels apart is one visual language doing two different jobs.
        this.marker = scene.add.ellipse(0, 0, 22, 11, 0x000000, 0)
            .setDepth(opts.markerDepth ?? d - 8);
        this.marker.setStrokeStyle(2, 0xffffff, 0.85);
        scene.tweens.add({
            targets: this.marker,
            scale: 1.22,
            alpha: 0.4,
            duration: 700,
            yoyo: true,
            repeat: -1,
            ease: 'Sine.easeInOut',
        });

        this.shadow = scene.add.ellipse(0, 0, 13, 6, 0x000000, 0.34)
            .setDepth(opts.shadowDepth ?? d - 10);

        // Trail ghosts are pre-allocated and recycled. A match is thousands of
        // frames; creating and destroying sprites per frame would churn.
        this.trail = [];
        for (let i = 0; i < 7; i++) {
            const t = scene.add.image(0, 0, KEY, 0)
                .setDepth(d - 2)
                .setAlpha(0)
                .setActive(false);
            this.trail.push(t);
        }
        this.trailAt = 0;
        this.trailClock = 0;

        this.sprite = scene.add.image(0, 0, KEY, 0).setDepth(d);

        this.frame = 0;
        this.spin = 0;        // accumulated rotation, in frames
        this.roll = 0;        // in-plane rotation, radians
        this.lastX = null;
        this.lastY = null;
        this.wasAir = 0;
    }

    /**
     * Put the ball at a projected point. `air` is how high off the ground it is,
     * in screen pixels; `groundY` is where its shadow belongs.
     */
    place(x, y, groundY, air = 0, delta = 16) {
        const s = this.sprite;
        if (!s || !s.active) return;

        // Spin from ground covered, not from a clock, so it reads as physical
        if (this.lastX !== null) {
            const moved = Math.hypot(x - this.lastX, y - this.lastY);
            // ~13px of travel per rotation frame: a hard shot blurs, a dribble
            // turns over slowly.
            this.spin += moved / 13;
            this.roll += (x - this.lastX) / 26;

            if (moved > 0.6) {
                this.frame = ((Math.round(this.spin) % FRAMES) + FRAMES) % FRAMES;
                s.setFrame(this.frame);
                s.setRotation(this.roll);
            }

            // Trail while it is genuinely flying, not while being dribbled
            this.trailClock += delta;
            if ((air > 5 || moved > 3.2) && this.trailClock > 34) {
                this.trailClock = 0;
                this._ghost(x, y);
            }
        }
        this.lastX = x;
        this.lastY = y;

        s.setPosition(x, y);
        this.marker.setPosition(x, groundY + 2);

        this.shadow.setPosition(x, groundY + 2);
        const k = Math.max(0.45, 1 - air / 130);
        this.shadow.setScale(k);
        this.shadow.setAlpha(0.34 * k);

        // Coming down: bounce dust the moment it lands
        if (this.wasAir > 12 && air <= 1) this.dust(x, groundY, 5);
        this.wasAir = air;
    }

    _ghost(x, y) {
        const t = this.trail[this.trailAt];
        this.trailAt = (this.trailAt + 1) % this.trail.length;
        if (!t || !t.scene) return;

        this.scene.tweens.killTweensOf(t);
        t.setActive(true).setPosition(x, y).setFrame(this.frame)
            .setRotation(this.roll).setAlpha(0.42).setScale(0.85);
        this.scene.tweens.add({
            targets: t,
            alpha: 0,
            scale: 0.5,
            duration: 240,
            onComplete: () => { if (t.scene) t.setActive(false); },
        });
    }

    /**
     * A strike. Squashes the ball along its direction of travel, throws a white
     * impact star, and kicks up grass. Called at the moment the ball leaves a
     * foot, so it lands on the same frame the pass starts.
     */
    kick(x, y, dirX = 1, dirY = 0, power = 1) {
        const s = this.sprite;
        if (!s || !s.active) return;

        // Squash across the strike, stretch along it
        this.scene.tweens.killTweensOf(s);
        s.setScale(1);
        this.scene.tweens.add({
            targets: s,
            scaleX: 1 + 0.34 * power,
            scaleY: 1 - 0.24 * power,
            duration: 70,
            yoyo: true,
            ease: 'Quad.easeOut',
            onComplete: () => { if (s.active) s.setScale(1); },
        });

        this.star(x, y, power);
        this.dust(x, y + 3, 4);

        // Kick it off with real spin already on it
        this.spin += 3 * power;
    }

    star(x, y, power = 1) {
        kickBurst(this.scene, x, y, this.sprite.depth + 1, power);
    }

    dust(x, y, n = 4) {
        turfDust(this.scene, x, y, this.sprite.depth - 1, n);
    }

    get active() { return !!(this.sprite && this.sprite.active); }

    destroy() {
        this.trail.forEach(t => t.destroy());
        this.sprite.destroy();
        this.shadow.destroy();
        this.marker.destroy();
    }
}
